/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package boffin;

import java.util.Scanner;

class App {
    public static double calculateBmi(int height, int weight) {
        final double IMPERIAL_CONV = 703.0;
        double bmi = (weight * IMPERIAL_CONV) / Math.pow(height, 2);
        return bmi;
    }

    public static void main(String[] args) {
        Scanner bob = new Scanner(System.in);

        System.out.print("Enter your height in inches: ");
        int height = bob.nextInt();

        System.out.print("Enter your weight to the nearest pound: ");
        int weight = bob.nextInt();

        double bmi = calculateBmi(height, weight);
        System.out.printf("Your BMI is %.1f\n", bmi);
    }
}
