/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package boffin;

import static spark.Spark.get;

import java.util.HashMap;

import spark.ModelAndView;
import spark.template.mustache.MustacheTemplateEngine;

public class Server {
    public static void main(String[] args) {
        get("/", (req, res) -> "<html><body><h1>Hello World!</h1></body></html>");

        get("/hello", (req, res) -> {
            // if (name == null) {
            // return "<html><body><form method='get'><label>Name: <input
            // name='name'></label><button>Submit</button><body></html>";
            // }
            // return "<html><body><h1>Hello " + name + "!</h1></body></html>";
            String name = req.queryParams("name");
            HashMap<String, Object> model = new HashMap<>();
            model.put("name", name);
            return new MustacheTemplateEngine().render(
                    new ModelAndView(model, "hello.mustache"));
        });

        get("/bmi", (req, res) -> {
            String heightStr = req.queryParams("height");
            String weightStr = req.queryParams("weight");
            HashMap<String, Object> model = new HashMap<>();

            if (heightStr != null && weightStr != null) {
                int height = Integer.parseInt(heightStr);
                int weight = Integer.parseInt(weightStr);
                double bmi = App.calculateBmi(height, weight);
                model.put("bmi", bmi);
            }

            return new MustacheTemplateEngine().render(
                    new ModelAndView(model, "bmi.mustache"));
        });
    }
}
